In [1]:
import pandas as pd
import numpy as np
import joblib

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [2]:
df = pd.read_csv("data.csv")
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [3]:
print(df.columns)

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'street', 'city',
       'statezip', 'country'],
      dtype='object')

In [4]:
numeric_df = df.select_dtypes(include=['int64', 'float64'])
numeric_df.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
0,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005
1,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0
2,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0
3,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0
4,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992

In [6]:
x = numeric_df[['bedrooms','bathrooms','floors','sqft_living']]
y = numeric_df.drop('price', axis=1)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [8]:
model = LinearRegression()
model.fit(X_train, y_train)

print("Model Trained Successfully")

Model Trained Successfully

In [9]:
y_pred = model.predict(X_test)

print(y_pred[:10])

[[ 3.00000000e+00  2.50000000e+00  1.46000000e+03  1.61300000e+03
   2.00000000e+00 -5.57237288e-15 -2.41565562e-14  3.00000000e+00
   1.18000000e+03  2.80000000e+02  2.00700000e+03 -4.43631682e-12]
 [ 5.00000000e+00  2.25000000e+00  2.00000000e+03  7.90000000e+03
   1.00000000e+00 -5.51902485e-15 -1.41501337e-14  4.00000000e+00
   1.30000000e+03  7.00000000e+02  1.98600000e+03 -2.83661239e-12]
 [ 3.00000000e+00  3.25000000e+00  2.94000000e+03  5.43200000e+03
   3.00000000e+00 -2.48092534e-15  3.00000000e+00  4.00000000e+00
   2.44000000e+03  5.00000000e+02  1.97800000e+03  2.00000000e+03]
 [ 3.00000000e+00  2.50000000e+00  2.20000000e+03  7.35000000e+03
   1.00000000e+00 -6.91668524e-15 -1.35311173e-14  5.00000000e+00
   1.57000000e+03  6.30000000e+02  1.98800000e+03 -2.73720195e-12]
 [ 3.00000000e+00  2.50000000e+00  1.72000000e+03  8.75500000e+03
   1.00000000e+00 -5.37122574e-15 -2.36442325e-14  3.00000000e+00
   1.00000000e+03  7.20000000e+02  1.98300000e+03  2.00900000e+03]
 [ 4.00000000e+00  2.50000000e+00  2.82000000e+03  8.40800000e+03
   2.00000000e+00 -4.39392813e-15 -1.30100775e-14  3.00000000e+00
   2.82000000e+03 -6.70524481e-13  2.01400000e+03 -2.80665062e-12]
 [ 4.00000000e+00  1.75000000e+00  2.12000000e+03  7.42000000e+03
   1.00000000e+00 -7.13857516e-16 -1.18759687e-16  4.00000000e+00
   1.06000000e+03  1.06000000e+03  1.95600000e+03 -3.08397652e-12]
 [ 4.00000000e+00  2.50000000e+00  2.09000000e+03  5.19500000e+03
   2.00000000e+00 -3.80443380e-15 -1.40698077e-14  3.00000000e+00
   2.09000000e+03 -1.00609293e-12  2.00700000e+03 -3.63787164e-12]
 [ 4.00000000e+00  2.25000000e+00  2.07000000e+03  7.50000000e+03
   2.00000000e+00  1.04301146e-16  4.68319984e-15  4.00000000e+00
   2.07000000e+03 -1.55708005e-12  1.97700000e+03 -3.05239645e-12]
 [ 4.00000000e+00  2.25000000e+00  2.11000000e+03  1.26530000e+04
   2.00000000e+00  1.27893640e-15  7.96523503e-15  4.00000000e+00
   2.11000000e+03 -1.43215870e-12  1.97200000e+03 -1.71874289e-12]]

In [10]:
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("RMSE:", rmse)

RMSE: 9.085945357486913e-12

In [12]:
print(y_test.shape)
print(y_pred.shape)

(920, 12)
(920, 12)

In [14]:
import pandas as pd
import numpy as np

predictions = pd.DataFrame({
    "Actual Price": np.ravel(y_test),
    "Predicted Price": np.ravel(y_pred)
})

predictions.to_csv("predictions.csv", index=False)

predictions.head()

   Actual Price  Predicted Price
0           3.0              3.0
1           2.5              2.5
2        1460.0           1460.0
3        1613.0           1613.0
4           2.0              2.0

In [15]:
joblib.dump(model, "trained_model.pkl")

print("Model Saved")

Model Saved

In [16]:
from google.colab import files

files.download("predictions.csv")
files.download("trained_model.pkl")